### ISSUE TITLE
可以上6.2？

### ISSUE THREAD

**Issue by Potterli20** [UJX6N/bbrplus-6.x_Mainline#1]
可以上6.2的kernel???
其实那个bbrplus的代码有没有变？？

**Comment by UJX6N** [comment]
已经上传了6.2的补丁和内核

代码的话，其实就是看看现在bbr有没什么改动，如果有改动而且可以同步到bbrplus的就同步一下

**Comment by UJX6N** [comment]
这个是基于v1的（就是google官方的bbr），看以后能不能加v2进去
