### ISSUE TITLE
可以上6.3？

### ISSUE THREAD

**Issue by Potterli20** [UJX6N/bbrplus-6.x_Mainline#2]
又是我，可以上kernel 6.3？

**Comment by UJX6N** [comment]
> 又是我，可以上kernel 6.3？

发布了，延迟因为6.3一直编译有问题，make deb-pkg通不过

现暂时改用不出源码包的make bindeb-pkg

**Comment by UJX6N** [comment]
> > > 又是我，可以上kernel 6.3？
> > 
> > 
> > 发布了，延迟因为6.3一直编译有问题，make deb-pkg通不过
> > 现暂时改用不出源码包的make bindeb-pkg
> 
> 这个能用在xanmod？还有那个编译是用云编译？还是？

暂时没有用云编译，要先研究一下
